#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

server:
  port: 8050

spring:
  application:
    name: E-Commerce
  main:
    allow-circular-references: true
  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5435/ecommerc
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
    show-sql: true
autenticazione:
      srvUrl: http://localhost:9100/api/utenti/cerca/email/
      userId: Ciccio
      password: 4567